theme: jekyll-theme-minimal
title: Amy's Nerdy Corner
description: Things I find interesting.
logo: logo.png

defaults:
  # _main
  - scope:
      path: ""
      type: main
    values:
      sidebar:
        nav: "main"
